### PR TITLE
Body element added in the periodic table of html elements

### PR DESCRIPTION
**Pull request by bikrambhattacharya**
Body element added by maintaining periodic table structure of html elements.

### CODE REVIEW

**Comment by bikrambhattacharya** [comment]
html elements periodic table is complete now
image 2

**Comment by bikrambhattacharya** [comment]
@MadeByMike  hello?

**Comment by MadeByMike** [comment]
@bikrambhattacharya Sorry! Notifications are like a fire hose sometimes.

**Comment by bikrambhattacharya** [comment]
@MadeByMike  It's okay.

**Pull request merged**
